[project]
name = "ducklake-to-xgboost"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.0.0",
    "adbc-driver-manager>=0.10.0",
    "pyarrow>=15.0.0",
    "xgboost>=2.0.0",
]
